our_site/account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("login/", views.PlannerLoginView.as_view(), name="login"),
    path("", views.PlannerLoginView.as_view(), name="login"),
    path("newAccount/", views.newAccount, name="newAccount"),
    path("logout/", views.logout_view, name="logout"),
]

our_site/our_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("planner/", include("planner.urls")),
    path("account/", include("account.urls")),
    path("", include("account.loginurl")),
    path("admin/", admin.site.urls),
]

our_site/planner/urls.py
from django.urls import path
from . import views

app_name = "planner"
urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),  # Main page where user views events
    path("dashboard/allevents/", views.dashboard, name="dashboard_all"),
    path("dashboard/myevents/", views.dashboard, name="dashboard_my"),
    path("dashboard/accevents/", views.dashboard, name="dashboard_accepted"),
    path("dashboard/invevents/", views.dashboard, name="dashboard_invited"),

    path("event_creation/", views.event_creation, name="event_creation"),  # Place to create and edit events
    path("<int:event_id>/edit_event/", views.edit_event, name="edit_event"),

    path('event/<int:event_id>/', views.event_home, name='event_home'),  # Places to view a specific event
    path('event_owned/<int:event_id>/', views.event_home_owned, name="event_home_owned"),
    #path('signupRoles/<int:event_id>/', views.signupRoles, name='signupRoles'),
    
    path("<int:event_id>/invitations/", views.invitations, name="invitations"),  # Changing info about an event
    path('<int:event_id>/addRoles', views.addRoles, name="addRoles"),
    path('<int:event_id>/handle_event/', views.handle_event, name='handle_event'),
    path('<int:role_id>/signupRoles', views.signupRoles, name='signupRoles')
    
]

our_site/planner/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    roles = models.ManyToManyField("Role", related_name="fulfilled_by")


class Event(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="events")
    name = models.CharField(max_length=30)
    date = models.DateField()
    description = models.CharField(max_length=200)
    location = models.CharField(max_length=50)
    invitees = models.ManyToManyField(Profile, related_name="invitations")
    attendees = models.ManyToManyField(Profile, related_name="attended_events")


class Role(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    event=models.ForeignKey(Event, on_delete=models.CASCADE, related_name="roles")
    amount = models.IntegerField()


def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()

our_site/planner/forms.py
from django import forms
from django.core.exceptions import ValidationError

from django.contrib.auth.forms import User


class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100, widget=forms.TextInput(
        attrs={'style': 'width: 250px; height: 300px; border: 1px solid #ccc; padding: 5px;'}))
    password = forms.CharField(label="Password", max_length=100, widget=forms.TextInput(
        attrs={'style': 'width: 250px; height: 30px; border: 1px solid #ccc; padding: 5px;'}))


def is_user_name(user_name: str) -> None:
    """
    This is a utility function for determining if a string is a valid username in the database.
    If the string is a valid username, the function returns None.
    If there is no user with this username, the function raises a ValidationError.

    :param user_name:
    """
    matching_users = User.objects.all().filter(username__exact=user_name)
    if len(matching_users) != 1:
        raise ValidationError("'{:s}' is not an existing user.".format(user_name), code="invalid user")


class SelectUserForm(forms.Form):
    """
    Base class form for getting the name of a user.
    Provides validation that the name of the user actually exists in the database.
    """
    user_name = forms.CharField(max_length=150, validators=[is_user_name])


class AddInvitationForm(SelectUserForm):
    user_name = forms.CharField(label="Username:", max_length=150, validators=[is_user_name])


class RemoveInvitationForm(SelectUserForm):
    pass

our_site/planner/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
import django.forms as forms
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import render

from .models import Event, User, Profile, Role
from .forms import AddInvitationForm, RemoveInvitationForm

from notifications.notify_email import send_notification


def dashboard(request) -> HttpResponse:
    """
    dashboard is the central "hub" of our website, where users can view all the events that they have created or have
    been invited to. The dashboard is actually made up of four slightly different html templates.
    Each template has a different "activated" button on the menu of 4 buttons to indicate what the shown events
    are being filtered by (all events, owned events, attending, and invited).

    :param request: The HTTP request for a page.
    :return: If the user is not logged in, an HTTP redirect to the login page.
             Otherwise, one of the four rendered templates corresponding to each of the filters.
    """
    if request.user.is_anonymous:
        return HttpResponseRedirect("/account/login/")

    owner = request.user.profile
    # Get the full url, because the last part of the url is the value by which to filter events
    filter_value = request.build_absolute_uri().split("/")[-2]

    match filter_value:
        case "allevents":
            template = loader.get_template("planner/dash_allevents.html")

            owned_events_list = list(Event.objects.all().filter(owner=owner))
            invited_list = list(Event.objects.all().filter(invitees__in=[owner]))
            attending_list = list(Event.objects.all().filter(attendees__in=[owner]))

            event_list = owned_events_list + invited_list + attending_list
        case "myevents":
            template = loader.get_template("planner/dash_myevents.html")
            owner = request.user.profile
            event_list = list(Event.objects.filter(owner_id=owner))
        case "accevents":
            template = loader.get_template("planner/dash_accevents.html")
            owner = request.user.profile
            event_list = list(Event.objects.all().filter(attendees__in=[owner]))
        case "invevents":
            template = loader.get_template("planner/dash_invevents.html")
            event_list = list(Event.objects.all().filter(invitees__in=[owner]))
        case _:
            return HttpResponseRedirect("/planner/dashboard/allevents")

    return HttpResponse(template.render(
        {
            "event_list": event_list,
            "owner": owner,
        },
        request
    ))


class EventBasicDetails(forms.Form):
    event_name = forms.CharField(label="Event Name:", max_length=30, required=True)
    event_date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], label="Event Date (yyyy-mm-dd):",
                                     required=True)
    event_description = forms.CharField(
        label="Event Description:",
        max_length=200,
        required=True,
        widget=forms.Textarea(attrs={'class': 'event-description', 'style': 'width: 763px; height: 172px'}),
    )
    event_location = forms.CharField(label="Event Location:", max_length=50, required=True)


def event_creation(request):
    if request.user.is_anonymous:  # User is redirected to log in if they are not logged in
        return HttpResponseRedirect("/account/login/")

    if request.method == "GET":
        template = loader.get_template("planner/event_creation.html")
        event_creation_form = EventBasicDetails()
        return HttpResponse(template.render({"event_creation_form": event_creation_form}, request))
    elif request.method == "POST":
        # It is acceptable to shove the data from this post into one form because currently only one form
        # leads to this page
        event_creation_form = EventBasicDetails(request.POST)
        # If the form is valid, save the new event and move to it's editing page
        # otherwise, just redisplay the form with its errors
        if event_creation_form.is_valid():
            event = Event(
                owner=request.user.profile,
                name=event_creation_form.cleaned_data["event_name"],
                date=event_creation_form.cleaned_data["event_date"],
                description=event_creation_form.cleaned_data["event_description"],
                location=event_creation_form.cleaned_data["event_location"],
            )
            event.save()
            if (username := request.user.username).endswith("@westmont.edu"):
                send_notification(username, "Your new event is live!", "Your event '{:s}' has been created!\n"
                                                                       "Go invite people now.".format(event.name))
            return HttpResponseRedirect("/planner/{:d}/edit_event".format(event.id))
        else:
            template = loader.get_template("planner/event_creation.html")
            return HttpResponse(template.render({"event_creation_form": event_creation_form}, request))


def event_specific_credentials(request, event_id) -> HttpResponseRedirect | Event:
    """
    This is a utility function that allows you to tell if a user has logged in and is the owner of
    an event. If this is the case, the Event record will be returned, and if not an HttpResponseRedirect.

    :param request: The HTTP request for a page
    :param event_id: the id of the event in the url
    :return: If the user is logged in as the owner of an event with the id event_id, that Event.
             Otherwise, an HttpResponseRedirect to the login page if the user isn't logged in,
             and an HttpResponseRedirect to the user's dashboard if they do not own the event
             or if the event does not exist.
    """
    if request.user.is_anonymous:
        return HttpResponseRedirect("/account/login/")

    event_getter = Event.objects.all().filter(id__exact=event_id)
    if len(event_getter) == 0:  # If the event to "edit" doesn't exist, redirect to dashboard
        return HttpResponseRedirect("/account/dashboard")
    event = Event.objects.all().filter(id__exact=event_id).get()  # otherwise, store it here

    user_profile_id = request.user.profile.id
    owner_profile_id = event.owner_id
    if user_profile_id != owner_profile_id:  # If the user does not own this event, they can't edit it
        return HttpResponseRedirect("/account/dashboard")

    return event


def edit_event(request, event_id: int) -> HttpResponse:
    """
    This view provides a way for user to edit the basic details of an event they own (the name, date, description,
    and location). Users are verified as the owners of the event using event_specific_credentials.

    :param request: The Http request for a page
    :param event_id: the id of the event that the user wants to edit
    :return: An HttpResponse of the rendered template planner/edit_event.html
    """
    event = event_specific_credentials(request, event_id)
    if isinstance(event, HttpResponseRedirect):
        return event

    # If a get, give the template to edit an event.
    # If a post, try to validate the form and save information,
    # and then give back the template to edit the event.
    template = loader.get_template("planner/edit_event.html")
    match request.method:
        case "GET":
            pass
        case "POST":
            # It is acceptable to shove the data from this post into one form because currently only one form
            # leads to this page
            posted_details = EventBasicDetails(request.POST)
            # If the form is valid, update the event and reload the page
            # otherwise, just redisplay the form with its errors
            if posted_details.is_valid():
                event.name = posted_details.cleaned_data["event_name"]
                event.date = posted_details.cleaned_data["event_date"]
                event.description = posted_details.cleaned_data["event_description"]
                event.location = posted_details.cleaned_data["event_location"]
                event.save()
                return HttpResponseRedirect("/planner/event_owned/{:d}/".format(event.id))

    if request.method == "POST":
        if "Add Invitees" in request.POST:
            return HttpResponseRedirect("/planner/{:d}/invitations/".format(event.id))

        # if "Save Changes" in request.POST:
        #     event.save()
        #     return HttpResponseRedirect("/planner/event_owned/{:d}/".format(event.id))

    basic_details = EventBasicDetails(initial={
        "event_name": str(event.name),
        "event_date": str(event.date),
        "event_description": str(event.description),
        "event_location": str(event.location),
    })
    return HttpResponse(
        template.render(
            {
                "basic_details": basic_details,
                "event_id": event.id,
            },
            request
        )
    )


def event_home_owned(request, event_id):
    if request.user.is_anonymous:
        return HttpResponseRedirect("/account/login/")

    event = Event.objects.all().filter(id__exact=event_id).get()
    invitees = event.invitees.all()
    attendees = event.attendees.all()

    user_profile_id = request.user.profile.id
    owner_profile_id = event.owner_id
    invitee_profile_ids = event.invitees.values_list('id', flat=True)
    roles_list = list(event.roles.all())

    if user_profile_id != owner_profile_id and user_profile_id not in invitee_profile_ids:
        return HttpResponseRedirect("/planner/dashboard")

    if user_profile_id != owner_profile_id:
        return HttpResponseRedirect("/planner/event/{:d}/".format(event.id))

    try:
        event = Event.objects.get(pk=event_id)
    except Event.DoesNotExist:
        raise Http404("Event does not exist")

    if request.method == "POST":
        if "Edit Event" in request.POST:

our_site/planner/templates/planner/dash_accevents.html
{% extends 'planner/dashboard.html' %}

{% block tabs %}
    <li><a href="{% url "planner:dashboard_all" %}" class="custom-text-color" style="color: #b41313">All Events</a></li>
    <li><a href="{% url "planner:dashboard_my" %}" class="custom-text-color" style="color: #b41313"style="color: #b41313">My Events</a></li>

    <li class="is-active">
        <a class="has-text-danger-dark" style="background-color: #ffd68b" id="Attending Events Filter">
            Accepted Events
        </a>
    </li>

    <li><a href="{% url "planner:dashboard_invited" %}" class="custom-text-color" style="color: #b41313">Invited Events</a></li>
{% endblock %}

our_site/planner/templates/planner/dash_allevents.html
{% extends 'planner/dashboard.html' %}

{% block tabs %}

    <li class="is-active">
        <a class="has-text-danger-dark" style="background-color: #ffd68b" id="All Events Filter">
            All Events
        </a>
    </li>

    <li><a href="{% url "planner:dashboard_my" %}" class="custom-text-color" style="color: #b41313">My Events</a></li>
    <li><a href="{% url "planner:dashboard_accepted" %}" class="custom-text-color" style="color: #b41313">Accepted Events</a></li>
    <li><a href="{% url "planner:dashboard_invited" %}" class="custom-text-color" style="color: #b41313">Invited Events</a></li>
{% endblock %}

our_site/planner/templates/planner/dash_invevents.html
{% extends 'planner/dashboard.html' %}

{% block tabs %}
    <li><a href="{% url "planner:dashboard_all" %}" class="custom-text-color" style="color: #b41313">All Events</a></li>
    <li><a href="{% url "planner:dashboard_my" %}" class="custom-text-color" style="color: #b41313">My Events</a></li>
    <li><a href="{% url "planner:dashboard_accepted" %}" class="custom-text-color" style="color: #b41313">Accepted Events</a></li>

    <li class="is-active">
        <a class="has-text-danger-dark" style="background-color: #ffd68b" id="Invited Events Filter">
            Invited Events
        </a>
    </li>

{% endblock %}

our_site/planner/templates/planner/dash_myevents.html
{% extends 'planner/dashboard.html' %}

{% block tabs %}
    <li><a href="{% url "planner:dashboard_all" %}" class="custom-text-color" style="color: #b41313">All Events</a></li>

    <li class="is-active">
        <a class="has-text-danger-dark" style="background-color: #ffd68b" id="My Events Filter">
            My Events
        </a>
    </li>

    <li><a href="{% url "planner:dashboard_accepted" %}" class="custom-text-color" style="color: #b41313">Accepted Events</a></li>
    <li><a href="{% url "planner:dashboard_invited" %}" class="custom-text-color" style="color: #b41313">Invited Events</a></li>
{% endblock %}

our_site/planner/templates/planner/dashboard.html
{% extends 'base.html' %}

{% block content %}

    <div class="tabs is-boxed is-centered is-large">
        <ul>
            {% block tabs %}

            {% endblock %}
        </ul>
    </div>

    {% for event in event_list %}
        <div class="box has-background-warning custom-text-color m-5 is-parent" style="color: #b41313">
            <div class="level">
                <div class="level-item">
                    <a
                            href="{% url 'planner:event_home' event.id %}"
                            class="has-text-weight-bold is-size-2 custom-text-color"
                            style="color: #b41313"
                            id="event-title-{{ forloop.counter }}">{{ event.name }}
                    </a>
                </div>
            </div>

            <div class="level">
                <div class="level-item is-size-4">
                    Hosted by: {{ event.owner.user }}
                </div>
                <div class="level-item is-size-4">
                    Where: {{ event.location }}
                </div>
                <div class="level-item is-size-4">
                    When: {{ event.date }}
                </div>
            </div>

            <div class="level">
                Description: {{ event.description }}
            </div>
        </div>
    {% endfor %}

{% endblock content %}
        

our_site/planner/templates/planner/edit_event.html
{% extends 'base.html' %}

{% block content %}
    
    <style>
        .eventdtls input[type="text"] {
            padding: 5px;
            margin-bottom: 30px;
        }

        .event-description {
            padding: 4px;
        }
    </style>

    <div class="container is-max-desktop">
        <div class="tile is-child is-warning notification is-12" style="background-color: rgb(238, 236, 236)">
            <p style="font-size: 50px; color: #900505; font-weight: bold">
                Confirm Event Details
            </p>
            <br>
            <form class="eventdtls" method="post" style="font-weight: bold; font-size: 20px">
                {% csrf_token %}

                <label class="label" style="font-size: 20px">
                    Event Name:
                    <br>
                    {{ basic_details.event_name }}
                </label>

                <label class="label" style="font-size: 20px">
                    Event Date (yyyy-mm-dd):
                    <br>
                    {{ basic_details.event_date }}
                </label>

                <label class="label" style="font-size: 20px">
                    Event Description
                    <br>
                    {{ basic_details.event_description }}
                </label>

                <label class="label" style="font-size: 20px">
                    Event Location:
                    <br>
                    {{ basic_details.event_location }}
                </label>

                <br>
                <input class="button is-warning" type="submit" value="Save Changes"/>
            </form>

            <br>

            <form action="{% url 'planner:addRoles' event_id=event_id  %}">
                {% csrf_token %}
                <input class="button is-warning" type="submit" value="Add Roles" name="Add Roles"/>
            </form>

            <br>

            <form method="post">
                {% csrf_token %}
                <input class="button is-warning" type="submit" value="Add Invitees" name="Add Invitees" id="Invite Button"/>
            </form>
        </div>
    </div>

{% endblock %}

our_site/planner/templates/planner/event_creation.html
{% extends 'base.html' %}

{% block content %}
    <div style="margin:30px; display: flex">
        <div class="column" style="flex: 1">
            
        </div>

        <form class="column" method="post" action="{% url "planner:event_creation" %}" style="flex: 2">
            {% csrf_token %}
          
            <div style="background-color: rgb(238, 236, 236); padding: 50px">
                <p>
                    <b style="font-size: 50px; color: #900505">
                        Basic Info
                    </b>
                </p>
                <p>
                    <i>
                        Give your event a name and add any details to make it unique!
                    </i>
                </p>
                <br>
                <div>
                    {{ event_creation_form.event_name.errors }}
                    <label class="label">
                        <p style="font-size: 20px">
                                Event Name:
                        </p>
                    </label>
                    {{ event_creation_form.event_name }} 
                    <p>
                        (30 characters max)
                    </p>
                </div>
                <br>
                <div>
                    {{ event_creation_form.event_description.errors }}
                    <label class="label">
                        <p style="font-size: 20px">
                            Description:
                        </p>
                    </label>
                    {{ event_creation_form.event_description }}
                    <p>
                        (200 characters max)
                    </p>
                </div>
            </div>
            <br>
            <div style="background-color: rgb(238, 236, 236); padding: 35px">
                <p>
                    <b style="font-size: 50px; color: #900505">
                        Location
                    </b>
                </p>
                <p>
                    <i>
                        Help your attendees know where to show up!
                    </i>
                </p>
                <br>
                <div>
                    {{ event_creation_form.event_location.errors }}
                    <label class="label">
                        <p style="font-size: 20px">
                            Event Location:
                        </p>
                    </label>
                    {{ event_creation_form.event_location }}
                    <p>
                        (50 characters max)
                    </p>
                </div>

            </div>
            <br>
            <div style="background-color: rgb(238, 236, 236); padding: 35px">
                <p>
                    <b style="font-size: 50px; color: #900505"> 
                        Date
                    </b>
                </p>
                <p>
                    <i>
                        Let your event-goers know when to be there!
                    </i>
                </p>
                <br>
                <div>
                    {{ event_creation_form.event_date.errors }}
                    <label class="label">
                        <p style="font-size: 20px">
                            Event Date (yyyy-mm-dd):
                        </p>
                    </label>
                    {{ event_creation_form.event_date }}
                </div>
            </div>
            <br>

            <div style="display: flex; justify-content: center; align-items: center">
                <input class="button is-warning" type="submit" value="Create Event!" style="height: 70px; width: 210px; font-weight: bold; font-size: 25px">
            </div>
            <br>
        </form>

        <div class="column"></div>

    </div>
{% endblock %}

our_site/planner/templates/planner/event_home.html
{% extends 'base.html' %}

{% block content %}

    <section class="section">
        <div class="container" style="background-color: #ebeaea; padding: 30px">
            <h1 class="title is-1 has-text-centered" style="color: #7f0000">{{ event.name }}</h1>
            <div class="content">
                <ul>
                    <p style="color:black; font-size:20px"><strong style="font-size:25px; color:#7f0000">Description:</strong> {{ event.description }}</p>
                    <p style="color:black; font-size:20px"><strong style="font-size:25px; color:#7f0000">Host:</strong> {{ event.owner.user }}</p>
                    <p style="color:black; font-size:20px"><strong style="font-size:25px; color:#7f0000">Location:</strong> {{ event.location }}</p>
                    <p style="color:black; font-size:20px"><strong style="font-size:25px; color:#7f0000">Date:</strong> {{ event.date }}</p>
                </ul>
            </div>

            <div class="columns">
                <div class="column has-text-left">
                    <h2 class="subtitle is-4">Attendees:</h2>
                    <ul>
                        {% for attendee in attendees %}
                            <li>{{ attendee.user.username }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="column has-text-left">
                    <h2 class="subtitle is-4">Invitees:</h2>
                    <ul>
                        {% for invitee in invitees %}
                            <li>{{ invitee.user.username }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="column has-text-left">
                    <h2 class="subtitle is-4">Roles:</h2>
                    <ul>
                        <div class='list-item'> 
                            {% for role in roles_list %}
                                <li>{{ role.name }}</li>
				                {% if user.profile in attendees %}
                                	 <form method="post" action="{% url 'planner:signupRoles' role.id %}">
                                         	{% csrf_token %}
                                                <button class="button is-small is-warning" type="submit" name="action" value="accept">Choose Role</button>
                                    </form>
                                {% endif %}
                            {% endfor %}
                                </div>
                            </div>        
                        </ul>
                        
                        <div class="column has-text-left">
                            <h2 class="subtitle is-4">My Roles:</h2>
                            <ul>
                                <div class='list-item'> 
                                    {% for sRoles in signedRoles %}
                                        <li>{{ sRoles.name }}</li>
                                    {% endfor %}
                                </div> 
                    </ul>  
                </div>
            </div>
        
            {% if user.profile in invitees %}
                <div class="buttons has-text-centered">
                    <form method="post" action="{% url 'planner:handle_event' event.id %}">
                        {% csrf_token %}
                        <button class="button is-medium is-warning" id="accept" type="submit" name="action" value="accept">Accept Invite</button>
                        <button class="button is-medium is-warning" id="decline" type="submit" name="action" value="decline">Decline Invite</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}

our_site/planner/templates/planner/event_home_owned.html
{% extends 'base.html' %}


{% block content %}

    <div class="container p-5"
         style="background-color: #ebeaea"
    >
        <h1 class="title is-1 has-text-centered" style="font-size:65px; color: #7f0000">{{ event.name }}</h1>
        <div class="content">
            <ul>
                <p style="color:black; font-size:20px"><strong style="font-size:25px; color:#7f0000">Description:</strong> {{ event.description }}</p>
                <p style="color:black; font-size:20px"><strong style="font-size:25px; color:#7f0000">Host:</strong> {{ event.owner.user }}</p>
                <p style="color:black; font-size:20px"><strong style="font-size:25px; color:#7f0000">Location:</strong> {{ event.location }}</p>
                <p style="color:black; font-size:20px"><strong style="font-size:25px; color:#7f0000">Date:</strong> {{ event.date }}</p>
            </ul>
        </div>

        <div class="columns">
            <div class="column has-text-left">
                <h2 class="subtitle is-4">Attendees:</h2>
                <ul>
                    {% for attendee in attendees %}
                        <li>{{ attendee.user.username }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="column has-text-left">
                <h2 class="subtitle is-4">Invitees:</h2>
                <ul>
                    {% for invitee in invitees %}
                        <li>{{ invitee.user.username }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="column has-text-left">
                <h2 class="subtitle is-4">Roles:</h2>
                <ul>
                    <div class='list-item'>
                        {% for role in roles_list %}
                            <li>{{ role.name }}</li>
                        {% endfor %}
                    </div>
                </ul>
            </div>
        </div>

        {% if user.profile in invitees %}
            <div class="buttons has-text-centered">
                <form method="post" action="{% url 'planner:handle_event' event.id %}">
                    {% csrf_token %}
                    <button class="button is-medium is-warning" id="accept" type="submit" name="action" value="accept">Accept Invite</button>
                    <button class="button is-medium is-warning" id="decline" type="submit" name="action" value="decline">Decline Invite</button>
                </form>
            </div>
        {% endif %}

        <form action="{{ edit_link }}">
            <input class="button is-warning is-size-5 mx-2" id="edit-event" type="submit" value="Edit Event">
        </form>
    </div>


{% endblock %}

our_site/planner/templates/planner/signupRoles.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="container">
            
            <b style="font-size: 40px; color: #900505"> You have successfully signed up for a role!</b>
        </div>
    </div>
        
{% endblock %}